### ISSUE TITLE
zatree 通过json 获取不到数据

### ISSUE THREAD

**Issue by thomasgogo** [spide4k/zatree#6]
zabbix 2.2.4.点击zatree 页面,出现如下错误
[20-Aug-2015 14:43:30] PHP Fatal error:  Uncaught exception 'Exception' with message 'API error -32602: Resource (itemvalue) does not exist' in /var/www/html/zabbix/zatree/ZabbixApiAbstract.class.php:254
Stack trace:
#0 /var/www/html/zabbix/zatree/ZabbixApiAbstract.class.php(8668): ZabbixApiAbstract->request('itemvalue.getIt...', Array, '')
#1 /var/www/html/zabbix/zatree/graph.php(238): ZabbixApiAbstract->getItemListFormat(Array, '')
#2 {main}

  thrown in /var/www/html/zabbix/zatree/ZabbixApiAbstract.class.php on line 254

**Comment by thomasgogo** [comment]
编辑API.php文件,添加如下这行
 'itemvalue'=>'CItemValue'
就有数据输出.我也是醉了.顺便自己记录下!
